/*
 * JM3001_CAR - starts
 */

DROP TABLE IF EXISTS JM3001_CAR;
CREATE TABLE JM3001_CAR 
  ( 
     MODEL_NUMBER NUMBER(6) PRIMARY KEY, 
     NAME         VARCHAR(20), 
     COLOR        VARCHAR(10) 
  );
/*
 * JM3001_CAR - ends
 */