DROP SCHEMA IF EXISTS JM3001_ONETOONE_UNI;

CREATE SCHEMA JM3001_ONETOONE_UNI;

CREATE TABLE JM3001_ONETOONE_UNI.CAR_DETAIL(
	ID BIGINT AUTO_INCREMENT,
	COLOR VARCHAR(10),
	MILEAGE DECIMAL,
	ABS BOOLEAN,
	PRIMARY KEY(ID)
);

CREATE TABLE JM3001_ONETOONE_UNI.CAR(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(10),
	CAR_DETAIL_ID BIGINT,
	PRIMARY KEY(ID),
	FOREIGN KEY(CAR_DETAIL_ID) REFERENCES JM3001_ONETOONE_UNI.CAR_DETAIL(ID)
);